export const data = [
    {
        title: 'Bronze',
        price: '(59.99$/month)',
        points: '3 points every 2 hour booked',
        studiorate: '55$ per hour',
        offshoot: '10% off photo and video',
        traking: 'Live Project Tracking',
        unlimited: '',
        offbeat: '',
        freeshoot: '',
        freebeat: '',
        offer: '',
        drink: '',
        promo: ''
    },
    {
        title: 'Silver',
        price: '(89.99$/Month)',
        points: '10 points every 2 hour booked',
        studiorate: '50$ per hour',
        offshoot: '15% off photo and video',
        traking: 'Live Project Tracking',
        unlimited: 'File Access Feature',
        offbeat: '',
        freeshoot: '',
        freebeat: '',
        offer: '',
        drink: '',
        promo: ''
    },
    {
        title: 'Gold',
        price: '(119.99$/Month)',
        points: '15 points every 2 hour booked',
        studiorate: '45$ per hour',
        offshoot: '20% off photo and video',
        traking: 'Live Project Tracking',
        unlimited: 'File Access Feature',
        offbeat: '10% off all beat production',
        freeshoot: '1 free shoot per year',
        freebeat: '',
        offer: '',
        drink: '',
        promo: ''
    },
    {
        title: 'Platinum',
        price: '(139.99$/Month)',
        points: '25 points every 2 hour booked',
        studiorate: '40$ per hour',
        offshoot: '30% off photo and video',
        traking: 'Live Project Tracking',
        unlimited: 'File Access Feature',
        offbeat: '10% off all beat production',
        freeshoot: '3 free shoots per year',
        freebeat: '3 Free beats per year',
        offer: 'Offer and special event first',
        drink: 'Complimentry drink during session \n(21 & older)',
        promo: 'Free song promotion'
    }
]